// =============================
// FILE: src/lib/quran-meta.ts (minimal 114 list; add arabicName later or fetch from API)
export type SurahMeta = {
number: number;
englishName: string;
arabicName?: string;
revelation?: "Meccan" | "Medinan";
};


export const surahs: SurahMeta[] = [
{ number: 1, englishName: "Al-Fatihah" },
{ number: 2, englishName: "Al-Baqarah" },
{ number: 3, englishName: "Ali 'Imran" },
{ number: 4, englishName: "An-Nisa'" },
{ number: 5, englishName: "Al-Ma'idah" },
{ number: 6, englishName: "Al-An'am" },
{ number: 7, englishName: "Al-A'raf" },
{ number: 8, englishName: "Al-Anfal" },
{ number: 9, englishName: "At-Tawbah" },
{ number: 10, englishName: "Yunus" },
{ number: 11, englishName: "Hud" },
{ number: 12, englishName: "Yusuf" },
{ number: 13, englishName: "Ar-Ra'd" },
{ number: 14, englishName: "Ibrahim" },
{ number: 15, englishName: "Al-Hijr" },
{ number: 16, englishName: "An-Nahl" },
{ number: 17, englishName: "Al-Isra'" },
{ number: 18, englishName: "Al-Kahf" },
{ number: 19, englishName: "Maryam" },
{ number: 20, englishName: "Ta-Ha" },
{ number: 21, englishName: "Al-Anbiya'" },
{ number: 22, englishName: "Al-Hajj" },
{ number: 23, englishName: "Al-Mu'minun" },
{ number: 24, englishName: "An-Nur" },
{ number: 25, englishName: "Al-Furqan" },
{ number: 26, englishName: "Ash-Shu'ara'" },
{ number: 27, englishName: "An-Naml" },
{ number: 28, englishName: "Al-Qasas" },
{ number: 29, englishName: "Al-'Ankabut" },
{ number: 30, englishName: "Ar-Rum" },
{ number: 31, englishName: "Luqman" },
{ number: 32, englishName: "As-Sajdah" },
{ number: 33, englishName: "Al-Ahzab" },
{ number: 34, englishName: "Saba'" },
{ number: 35, englishName: "Fatir" },
{ number: 36, englishName: "Ya-Sin" },
{ number: 37, englishName: "As-Saffat" },
{ number: 38, englishName: "Sad" },
{ number: 39, englishName: "Az-Zumar" },
{ number: 40, englishName: "Ghafir" },
{ number: 41, englishName: "Fussilat" },
{ number: 42, englishName: "Ash-Shura" },
{ number: 43, englishName: "Az-Zukhruf" },
{ number: 44, englishName: "Ad-Dukhan" },
{ number: 45, englishName: "Al-Jathiyah" },
{ number: 46, englishName: "Al-Ahqaf" },
{ number: 47, englishName: "Muhammad" },
{ number: 48, englishName: "Al-Fath" },
{ number: 49, englishName: "Al-Hujurat" },
{ number: 50, englishName: "Qaf" },
{ number: 51, englishName: "Adh-Dhariyat" },
{ number: 52, englishName: "At-Tur" },
{ number: 53, englishName: "An-Najm" },
{ number: 54, englishName: "Al-Qamar" },
{ number: 55, englishName: "Ar-Rahman" },
{ number: 56, englishName: "Al-Waqi'ah" },
{ number: 57, englishName: "Al-Hadid" },
{ number: 58, englishName: "Al-Mujadila" },
{ number: 59, englishName: "Al-Hashr" },
{ number: 60, englishName: "Al-Mumtahanah" },
{ number: 61, englishName: "As-Saff" },
{ number: 62, englishName: "Al-Jumu'ah" },
{ number: 63, englishName: "Al-Munafiqun" },
{ number: 64, englishName: "At-Taghabun" },
{ number: 65, englishName: "At-Talaq" },
{ number: 66, englishName: "At-Tahrim" },
{ number: 67, englishName: "Al-Mulk" },
{ number: 68, englishName: "Al-Qalam" },
{ number: 69, englishName: "Al-Haqqah" },
{ number: 70, englishName: "Al-Ma'arij" },
{ number: 71, englishName: "Nuh" },
{ number: 72, englishName: "Al-Jinn" },
{ number: 73, englishName: "Al-Muzzammil" },
{ number: 74, englishName: "Al-Muddaththir" },
{ number: 75, englishName: "Al-Qiyamah" },
{ number: 76, englishName: "Al-Insan" },
{ number: 77, englishName: "Al-Mursalat" },
{ number: 78, englishName: "An-Naba'" },
{ number: 79, englishName: "An-Nazi'at" },
{ number: 80, englishName: "'Abasa" },
{ number: 81, englishName: "At-Takwir" },
{ number: 82, englishName: "Al-Infitar" },
{ number: 83, englishName: "Al-Mutaffifin" },
{ number: 84, englishName: "Al-Inshiqaq" },
{ number: 85, englishName: "Al-Buruj" },
{ number: 86, englishName: "At-Tariq" },
{ number: 87, englishName: "Al-A'la" },
{ number: 88, englishName: "Al-Ghashiyah" },
{ number: 89, englishName: "Al-Fajr" },
{ number: 90, englishName: "Al-Balad" },
{ number: 91, englishName: "Ash-Shams" },
{ number: 92, englishName: "Al-Layl" },
{ number: 93, englishName: "Ad-Duha" },
{ number: 94, englishName: "Ash-Sharh" },
{ number: 95, englishName: "At-Tin" },
{ number: 96, englishName: "Al-'Alaq" },
{ number: 97, englishName: "Al-Qadr" },
{ number: 98, englishName: "Al-Bayyinah" },
{ number: 99, englishName: "Az-Zalzalah" },
{ number: 100, englishName: "Al-'Adiyat" },
{ number: 101, englishName: "Al-Qari'ah" },
{ number: 102, englishName: "At-Takathur" },
{ number: 103, englishName: "Al-'Asr" },
{ number: 104, englishName: "Al-Humazah" },
{ number: 105, englishName: "Al-Fil" },
{ number: 106, englishName: "Quraysh" },
{ number: 107, englishName: "Al-Ma'un" },
{ number: 108, englishName: "Al-Kawthar" },
{ number: 109, englishName: "Al-Kafirun" },
{ number: 110, englishName: "An-Nasr" },
{ number: 111, englishName: "Al-Masad" },
{ number: 112, englishName: "Al-Ikhlas" },
{ number: 113, englishName: "Al-Falaq" },
{ number: 114, englishName: "An-Nas" },
];