// src/app/hackathon-helper/report/page.tsx
//
// Validation dashboard for the hackathon. Reads
//   scripts/output/batch-validation-summary.json    (from plot-metrics.py)
//   scripts/output/per-word/r{id}_s{NNN}.json       (from batch-validate.py)
// and renders a presentation-ready report: top-line stats, per-surah table,
// per-word distribution buckets, and the worst-N words across the whole run.
//
// All numbers come straight from the files on disk — no live computation, no
// API calls, no dependencies on the Quran.com API at view time. Generated by
// running:
//     scripts/.venv/bin/python scripts/batch-validate.py --reciter-id 7 --surahs 1,36,49,55,56,67,78-114
//     scripts/.venv/bin/python scripts/plot-metrics.py
// from the repo root.

import { promises as fs } from "node:fs";
import path from "node:path";
import Link from "next/link";
import ReportDashboard, { type ReportData, type Summary, type WorstWord } from "./ReportDashboard";

export const metadata = { title: "Validation Report · Hackathon" };
export const dynamic = "force-dynamic";

const OUTPUT_DIR = path.join(process.cwd(), "scripts", "output");
const SUMMARY_JSON = path.join(OUTPUT_DIR, "batch-validation-summary.json");
const PER_WORD_DIR = path.join(OUTPUT_DIR, "per-word");
const PNG_PUBLIC = "/hackathon-helper/report/batch-validation.png";
// We copy the matplotlib PNG into /public/hackathon-helper/report/ so the
// browser can fetch it; the script writes to scripts/output/, which isn't
// served as a static asset.
const PNG_DEST = path.join(process.cwd(), "public", "hackathon-helper", "report", "batch-validation.png");
const PNG_SOURCE = path.join(OUTPUT_DIR, "batch-validation.png");

async function copyPngIfNewer(): Promise<boolean> {
  try {
    const src = await fs.stat(PNG_SOURCE);
    let needsCopy = true;
    try {
      const dst = await fs.stat(PNG_DEST);
      needsCopy = src.mtimeMs > dst.mtimeMs;
    } catch {
      // dst missing
    }
    if (needsCopy) {
      await fs.mkdir(path.dirname(PNG_DEST), { recursive: true });
      await fs.copyFile(PNG_SOURCE, PNG_DEST);
    }
    return true;
  } catch {
    return false;
  }
}

async function loadReport(): Promise<ReportData | null> {
  let summary: Summary;
  try {
    const raw = await fs.readFile(SUMMARY_JSON, "utf-8");
    summary = JSON.parse(raw) as Summary;
  } catch {
    return null;
  }

  // Walk per-word files for: (a) worst-N words across the whole run,
  //                          (b) per-surah delta details for the drill-down table.
  const allWorst: WorstWord[] = [];
  const perSurahPairs: Record<number, WorstWord[]> = {};
  let perWordFileCount = 0;
  try {
    const files = await fs.readdir(PER_WORD_DIR);
    for (const f of files) {
      if (!f.endsWith(".json")) continue;
      try {
        const raw = await fs.readFile(path.join(PER_WORD_DIR, f), "utf-8");
        const data = JSON.parse(raw) as {
          surah: number;
          pairs: Array<{
            verseNum: number;
            wordIndex: number;
            predicted_start: number;
            predicted_end?: number;
            reference_start_ms: number | null;
            reference_end_ms: number | null;
            delta_ms: number | null;
          }>;
        };
        perWordFileCount += 1;
        const surahPairs: WorstWord[] = [];
        for (const pair of data.pairs ?? []) {
          if (pair.delta_ms === null || pair.reference_start_ms === null) continue;
          const entry: WorstWord = {
            surah: data.surah,
            verseNum: pair.verseNum,
            wordIndex: pair.wordIndex,
            predictedStartSec: pair.predicted_start,
            referenceStartSec: pair.reference_start_ms / 1000,
            deltaMs: pair.delta_ms,
          };
          surahPairs.push(entry);
          allWorst.push(entry);
        }
        perSurahPairs[data.surah] = surahPairs;
      } catch {
        // skip malformed file
      }
    }
  } catch {
    // directory missing — report will still render summary
  }

  allWorst.sort((a, b) => b.deltaMs - a.deltaMs);
  const top30 = allWorst.slice(0, 30);

  return {
    summary,
    worstWords: top30,
    perWordFileCount,
    perSurahPairs,
  };
}

export default async function ReportPage() {
  const [report, pngAvailable] = await Promise.all([loadReport(), copyPngIfNewer()]);

  if (!report) {
    return (
      <div className="min-h-screen bg-background text-foreground">
        <div className="mx-auto max-w-3xl px-6 py-16">
          <div className="text-xs uppercase tracking-widest text-muted-foreground mb-2">
            Quran.foundation Hackathon · Validation Report
          </div>
          <h1 className="text-3xl font-bold mb-4">Validation report not yet generated</h1>
          <p className="text-muted-foreground mb-4">
            Run the batch validator + plotter from the repo root, then refresh:
          </p>
          <pre className="rounded-md bg-zinc-950 text-zinc-200 font-mono text-xs p-4 overflow-auto">
{`scripts/.venv/bin/python scripts/batch-validate.py --reciter-id 7 \\
  --surahs 1,36,49,55,56,67,78-114
scripts/.venv/bin/python scripts/plot-metrics.py`}
          </pre>
          <div className="mt-6">
            <Link href="/hackathon-helper" className="text-sm underline">
              ← Back to /hackathon-helper
            </Link>
          </div>
        </div>
      </div>
    );
  }

  return <ReportDashboard data={report} pngUrl={pngAvailable ? PNG_PUBLIC : null} />;
}
